# Generated by Django 2.2.1 on 2019-05-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.Item')),
            ],
        ),
    ]
