# Generated by Django 2.2.1 on 2019-05-20 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_auto_20190520_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_picture',
            field=models.FileField(default='No picture', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.Customer'),
        ),
    ]
