# Generated by Django 2.2.1 on 2019-05-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrecommendation', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_target_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
