# Generated by Django 2.2.1 on 2019-05-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrecommendation', '0003_auto_20190528_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_target_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
