# Generated by Django 2.2.1 on 2019-05-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrecommendation', '0004_auto_20190528_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_address', models.CharField(max_length=200)),
                ('hotel_location', models.CharField(max_length=200)),
                ('hotel_latitude', models.DecimalField(decimal_places=15, max_digits=15)),
                ('hotel_longitude', models.DecimalField(decimal_places=15, max_digits=15)),
                ('hotel_room_type', models.CharField(choices=[('D', 'Double'), ('F', 'Family'), ('S', 'Single'), ('T', 'Twin')], default='S', max_length=1)),
                ('hotel_night_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('hotel_disability_access', models.BooleanField()),
                ('hotel_swimming_pool', models.BooleanField()),
                ('hotel_breakfast_available', models.BooleanField()),
                ('hotel_michelin_restaurant', models.BooleanField()),
                ('hotel_user_reviews', models.BigIntegerField()),
            ],
        ),
    ]
