# Generated by Django 2.2.1 on 2019-05-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrecommendation', '0005_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
