# Generated by Django 2.2.1 on 2019-05-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrecommendation', '0006_auto_20190528_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_note', models.IntegerField()),
                ('rating_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelrecommendation.Hotel')),
                ('rating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelrecommendation.User')),
            ],
        ),
    ]
