# Generated by Django 2.2.1 on 2019-06-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrecommendation', '0008_loginstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_action_date', models.DateTimeField(auto_now_add=True)),
                ('log_instance_id', models.BigIntegerField()),
                ('log_action_description', models.CharField(max_length=2000)),
            ],
        ),
    ]
