# Generated by Django 2.2.1 on 2019-06-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrecommendation', '0009_logaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_comment', models.CharField(max_length=2000)),
                ('log_about', models.CharField(max_length=2000)),
            ],
        ),
    ]
