# Generated by Django 2.2.1 on 2019-06-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrecommendation', '0010_logcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcomment',
            name='log_instance_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
