# Generated by Django 2.2.1 on 2019-06-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrecommendation', '0011_logcomment_log_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcomment',
            name='log_radio1',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
