# Generated by Django 2.2.1 on 2019-06-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrecommendation', '0012_logcomment_log_radio1'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_type',
            field=models.IntegerField(default=-1),
        ),
    ]
