# Generated by Django 2.2.1 on 2019-08-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrecommendation', '0015_hotel_hotel_location_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginstance',
            name='log_identification_string',
            field=models.CharField(default='not provided', max_length=200),
        ),
    ]
