# Generated by Django 2.2.1 on 2019-08-23 09:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrecommendation', '0016_loginstance_log_identification_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_recommendation_hotel', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('cache_description', models.CharField(max_length=2000)),
                ('cache_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelrecommendation.User')),
            ],
        ),
        migrations.CreateModel(
            name='CacheClosest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_description', models.CharField(max_length=2000)),
                ('cache_method', models.IntegerField()),
                ('cache_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelrecommendation.User')),
            ],
        ),
    ]
