# Generated by Django 2.2.1 on 2019-05-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(max_length=200)),
                ('user_lastname', models.CharField(max_length=200)),
                ('user_age', models.BigIntegerField()),
                ('user_target_price', models.BigIntegerField()),
                ('user_disable', models.BooleanField()),
                ('user_is_married', models.BooleanField()),
                ('user_have_kids', models.BooleanField()),
            ],
        ),
    ]
