# Generated by Django 2.2.1 on 2019-05-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='similarity',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='similarity',
            name='object_ctype',
        ),
        migrations.RemoveField(
            model_name='similarity',
            name='related_object_ctype',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='Similarity',
        ),
    ]
